# The URL the site will be built for
base_url = "https://belmoussaoui.com"

title = "Bilal Elmoussaoui"
description = "Personal blog & portfolio"
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
default_language = "en"
theme = "serene"
taxonomies = [
    { name = "tags" },       # Keep this
    { name = "categories" }, # Keep this
]
[markdown]
highlight_code = true
highlight_theme = "nord" # The highlight theme, choose one at https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
render_emoji = true

[extra]
links = [
    { name = "GitHub", icon = "github", url = "https://github.com/bilelmoussaoui" },
    { name = "Gitlab", icon = "gitlab", url = "https://gitlab.gnome.org/bilelmoussaoui" },
    { name = "LinkedIn", icon = "linkedin", url = "https://www.linkedin.com/in/bil-elmoussaoui/" },
    { name = "Email", icon = "email", url = "mailto:bil.elmoussaoui@gmail.com" },
]
sections = [
    { name = "blog", path = "/blog", is_external = false },
    { name = "projects", path = "/projects", is_external = false },
]
blog_categorized = true # Whether to categorize blog posts
back_to_top = true # Whether to show back-to-top button on post pages
blog_section_path = "/blog"
homepage_layout = "about"
nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","
name = "Bilal Elmoussaoui" # Your name
id = "bilelmoussaoui" # Your id/username/handle
show_id = false
bio = "Software Engineer @ Red Hat" # Your bio
avatar = "avatar.jpg" # Your avatar
footer_copyright = "Bilal Elmoussaoui"

toc = true              # Whether to show Table-Of-Contents by default
copy = true
outdate_alert = true
comment = false         # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = true     # Whether to display tags on post pages by default
truncate_summary = true # Whether to truncate the summary of a post by default

outdate_alert_days = 365
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
