on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
  codespell:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          path: content/blog
          ignore_words_list: "crate"
          skip: "*.svg"
          builtin: "clear,rare,informal,code,names"
