on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.16.1-1
        env:
          BUILD_THEMES: false
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  codespell:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          path: content/blog
          ignore_words_list: "crate,gir,mut"
          skip: "*.svg"
          builtin: "clear,rare,informal,code,names"
