on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_THEMES: false
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  typos:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master